<a href="https://colab.research.google.com/github/manasohara1/Python-Data-Analytics/blob/main/Python_Data_Analysis_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
my_dictionary={
    "Name": "Manas Ohara",
    "State":"Maharashtra",
    "Country": "India"
}
for key,values in my_dictionary.items():
  print(key,":",values,"\n")

Name : Manas Ohara 

State : Maharashtra 

Country : India 



## map(function_name,list_name) in list : so function given in 1st param will be applied to each and every element of that list.

# For e.g,


In [2]:
#creating list first
my_list=[i for i in range(1,11)]
print(my_list)
#creating function for this list which will increment the value
def inc(x):
  return x+1
print(list(map(inc,my_list)))

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
[2, 3, 4, 5, 6, 7, 8, 9, 10, 11]


## Lambda Function : So in previous e.g we created function defination which increased the lines of code. So lambda gives you ability to write function defination inside the map function
#For e.g,

In [3]:
list(map((lambda x:x+1),my_list))

[2, 3, 4, 5, 6, 7, 8, 9, 10, 11]

### filter() :  it behaves same like lambda but takes out only those elements  which are returning true condition for function.

##For e.g,

In [4]:
#creating list
my_list=[i for i in range(0,300,9)]
print("Original list :",my_list)
print("Filtered out list :",list(filter((lambda x:(x%2==0 and x<150)),my_list)))

Original list : [0, 9, 18, 27, 36, 45, 54, 63, 72, 81, 90, 99, 108, 117, 126, 135, 144, 153, 162, 171, 180, 189, 198, 207, 216, 225, 234, 243, 252, 261, 270, 279, 288, 297]
Filtered out list : [0, 18, 36, 54, 72, 90, 108, 126, 144]


# **Numpy**

In [5]:
import numpy as np

In [6]:
a=np.array([1,2,3])
print(type(a))
print(a.dtype)

<class 'numpy.ndarray'>
int64


ndim : for getting axes

size : to get array length

shape : to get it's shape

itemsize : to give actual memory taken by each element in numpy array (in bytes)

In [7]:
print(a.ndim)
print(a.size)
print(a.shape)

1
3
(3,)


In [8]:
#cretaing 2-d array now
b=np.array([[1.8,8.5],[2.4,5.1]])
print('array : ',b)
print('data type :',b.dtype)
print('dimensions : ',b.ndim)
print('size :',b.size)
print('shape :',b.shape)
print('itemsize :',b.itemsize)

array :  [[1.8 8.5]
 [2.4 5.1]]
data type : float64
dimensions :  2
size : 4
shape : (2, 2)
itemsize : 8


Note: array() in numpy can also accept tuples or sequence of tuples while creation or mixture of lis+tuples(e.g --> []+()+())

In [9]:
c=np.array(((1,2,3),(7,9,3)))
c[0,1]=99
c

array([[ 1, 99,  3],
       [ 7,  9,  3]])

## Intrinsic Creation of array

In [10]:
a=np.zeros((3,3))
b=np.ones((3,3))
print(a,'\n\n',b)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]] 

 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [11]:
my_list=[i for i in range(0,150,6)]
my_np_list=np.array(my_list)
print(list(filter((lambda x:(x%2==0 and (x>40 and x<100))),my_np_list)))

[42, 48, 54, 60, 66, 72, 78, 84, 90, 96]


In [12]:
arranged_np_array=np.arange(0,100,13)
print('Arranged np array : ',arranged_np_array)
reshaped_arranged_np_array=np.arange(1,10).reshape(3,3)
print('Reshaped Arranged Array : \n',reshaped_arranged_np_array)

Arranged np array :  [ 0 13 26 39 52 65 78 91]
Reshaped Arranged Array : 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


np. linspace(start,end+1,total_nums you want in that interval) -> it takes 3 args 

start -> starting point

end+1-> ending point+1

total_nums-> total nums you want in the same interval size

For e.g,

In [13]:
linspaced_np_array=np.linspace(0,10,5)
linspaced_np_array
# so this array contains such 5 numbers between range 0 to 10 with an equal interval)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

#np.random

In [14]:
randomized_np_array=np.random.random((3,3))
randomized_np_array

array([[0.55092362, 0.54320045, 0.70545808],
       [0.23447169, 0.94180458, 0.29915672],
       [0.04411142, 0.04329286, 0.01670253]])

#basic operations on numpy array

In [15]:
a=np.arange(1,11)
b=np.arange(11,21)
print(a)
print(b)
print('a+b : \n',a+b)
print('\n a-b :\n',a-b)
print('\n a/b :\n',a/b)
print('\n a*b',a*b)

[ 1  2  3  4  5  6  7  8  9 10]
[11 12 13 14 15 16 17 18 19 20]
a+b : 
 [12 14 16 18 20 22 24 26 28 30]

 a-b :
 [-10 -10 -10 -10 -10 -10 -10 -10 -10 -10]

 a/b :
 [0.09090909 0.16666667 0.23076923 0.28571429 0.33333333 0.375
 0.41176471 0.44444444 0.47368421 0.5       ]

 a*b [ 11  24  39  56  75  96 119 144 171 200]


In [16]:
squared_np_array=np.array([i**2 for i in range(1,10)])
print('Array of squares :',squared_np_array)
print('\n Squared Root : ',np.sqrt(squared_np_array))
print('\n sin : ',np.sin(squared_np_array))
print('\n cos : ',np.cos(squared_np_array))
print('\n tan : ',np.tan(squared_np_array))


Array of squares : [ 1  4  9 16 25 36 49 64 81]

 Squared Root :  [1. 2. 3. 4. 5. 6. 7. 8. 9.]

 sin :  [ 0.84147098 -0.7568025   0.41211849 -0.28790332 -0.13235175 -0.99177885
 -0.95375265  0.92002604 -0.62988799]

 cos :  [ 0.54030231 -0.65364362 -0.91113026 -0.95765948  0.99120281 -0.12796369
  0.30059254  0.39185723  0.77668598]

 tan :  [ 1.55740772  1.15782128 -0.45231566  0.30063224 -0.13352641  7.75047091
 -3.17290855  2.34786031 -0.81099442]


#Basic Operations on Numpy Matrix

In [17]:
b=np.arange(45,54).reshape((3,3))
b
c=np.arange(1,10).reshape((3,3))
c

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# **matrix multiplication confusion**

In [18]:
print("b x c : \n",b*c,'\n')
#this is wrong matrix multiplication accordig to lin algebra
print('b.c',np.dot(b,c),'\n')
print('c.b',np.dot(c,b),'\n')

b x c : 
 [[ 45  92 141]
 [192 245 300]
 [357 416 477]] 

b.c [[558 696 834]
 [594 741 888]
 [630 786 942]] 

c.b [[ 294  300  306]
 [ 726  741  756]
 [1158 1182 1206]] 



In [19]:
a=np.array([[2,3,8],[1,4,2],[2,3,5]])
b=np.array([[1,1,3],[2,4,1],[3,5,7]])
np.dot(a,b)

array([[32, 54, 65],
       [15, 27, 21],
       [23, 39, 44]])

In [20]:
a=np.arange(0,10)
print(a)
a+=1
print(a)

[0 1 2 3 4 5 6 7 8 9]
[ 1  2  3  4  5  6  7  8  9 10]


In [21]:
a=np.arange(1,11)
print(a)
a=np.log(a)
print(a)
a=np.sin(a)
print(a)
a=np.array([i**2 for i in range(1,11)])
print(a)
a=np.sqrt(a)
print(a)


[ 1  2  3  4  5  6  7  8  9 10]
[0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947
 1.94591015 2.07944154 2.19722458 2.30258509]
[0.         0.63896128 0.89057704 0.98302774 0.99925351 0.97568681
 0.93046593 0.87340508 0.81012663 0.74398034]
[  1   4   9  16  25  36  49  64  81 100]
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


In [22]:
a=np.random.random(10)
a
print('Sum',a.sum())
print('Min',a.min())
print('Max',a.max())
print('Mean',a.mean())
print('std',a.std())

Sum 4.241919511468853
Min 0.012691788960889405
Max 0.9690710411578357
Mean 0.42419195114688535
std 0.35975379505652333


# Indexing,Slicing,Iterating

In [23]:
a=np.random.random(10)
print(a)
print(a[1])
print(a[-1])

[0.23261498 0.74494364 0.18736707 0.27819223 0.23691816 0.5427632
 0.03244516 0.29971481 0.5565903  0.01587892]
0.7449436422912314
0.01587892067431229


In [24]:
a=np.random.randn(1,9).reshape((3,3))
print(a,"\n")
print(a[1:])

[[-1.43356027  0.12096791 -0.47257941]
 [ 1.34516812 -0.2837494  -1.17963545]
 [ 1.63705387 -0.57955527  0.3735519 ]] 

[[ 1.34516812 -0.2837494  -1.17963545]
 [ 1.63705387 -0.57955527  0.3735519 ]]


In [25]:
for i in a.flat:
  print(i)

-1.4335602705580965
0.12096790878314022
-0.47257941493540595
1.3451681215622613
-0.28374939769838964
-1.1796354486678058
1.6370538730991324
-0.5795552668566382
0.37355189567494157


np.apply_along_axis(function to apply,axis,array_name)

function-> it can be any function either self defined or built-in

if axis->0 , function given in bracket is applied column wise

if axis->1 , function given in bracket is applied row wise

In [26]:
a=np.arange(43,52).reshape((3,3))
print(a)
print(np.apply_along_axis(np.mean,axis=0,arr=a))  #col-wise
print(np.apply_along_axis(np.mean,axis=1,arr=a))  #row-wise
print(np.apply_along_axis(np.sum,axis=0,arr=a))

[[43 44 45]
 [46 47 48]
 [49 50 51]]
[46. 47. 48.]
[44. 47. 50.]
[138 141 144]


In [27]:
a=np.array([i for i in range(131,140)]).reshape((3,3))
def div_by_element(x):
    return x/2
print(np.apply_along_axis(div_by_element,axis=0,arr=a))

[[65.5 66.  66.5]
 [67.  67.5 68. ]
 [68.5 69.  69.5]]


shape manupulation

In [28]:
a=np.array([i for i in range(0,500,25)])
mask=a>=250
a=a[mask]
len(a)
a.reshape((5,2))

array([[250, 275],
       [300, 325],
       [350, 375],
       [400, 425],
       [450, 475]])

ravel()-> it is used for any n-d array into 1-d array

In [29]:
a=np.random.random((8,5))
print('shape a:',a.shape,'\n')
print(a)
b=a.ravel()
print('\n',b,'\n')
print('b shape : ',b.shape)

shape a: (8, 5) 

[[0.18838124 0.49672242 0.61891068 0.71618093 0.99097892]
 [0.66526768 0.78400962 0.1212977  0.36504714 0.37438009]
 [0.90610708 0.47618523 0.65697962 0.31749501 0.16851063]
 [0.97858072 0.56946835 0.53059203 0.65270976 0.56772824]
 [0.24101718 0.7840351  0.97221926 0.11677399 0.53223848]
 [0.26103005 0.96996871 0.47569502 0.21918475 0.89403387]
 [0.7011463  0.82848488 0.4119063  0.30359869 0.58878301]
 [0.00455831 0.44754761 0.53878301 0.00811508 0.23976046]]

 [0.18838124 0.49672242 0.61891068 0.71618093 0.99097892 0.66526768
 0.78400962 0.1212977  0.36504714 0.37438009 0.90610708 0.47618523
 0.65697962 0.31749501 0.16851063 0.97858072 0.56946835 0.53059203
 0.65270976 0.56772824 0.24101718 0.7840351  0.97221926 0.11677399
 0.53223848 0.26103005 0.96996871 0.47569502 0.21918475 0.89403387
 0.7011463  0.82848488 0.4119063  0.30359869 0.58878301 0.00455831
 0.44754761 0.53878301 0.00811508 0.23976046] 

b shape :  (40,)


In [30]:
a=np.random.random((3,3))
print(a,'\n')
print(a.transpose())

[[0.49693173 0.42795137 0.1307878 ]
 [0.74142989 0.41162943 0.83590751]
 [0.5015838  0.06228377 0.55984816]] 

[[0.49693173 0.74142989 0.5015838 ]
 [0.42795137 0.41162943 0.06228377]
 [0.1307878  0.83590751 0.55984816]]


##Array Manupulation

Joining Arrays

hstack(),vstack()

Generally these functions are used with multi-dimensional array

In [31]:
a=np.ones((3,3))
b=np.zeros((3,3))
c=np.hstack((a,b))
d=np.vstack((a,b))
print('hsatcked :\n',c,'\n vsatcked :\n',d)

hsatcked :
 [[1. 1. 1. 0. 0. 0.]
 [1. 1. 1. 0. 0. 0.]
 [1. 1. 1. 0. 0. 0.]] 
 vsatcked :
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [32]:
a=np.random.random((5,))
b=np.random.random((5,))
c=np.random.random((5,))
d=np.row_stack((a,b,c))
d
e=np.column_stack((a,b,c))
e


array([[0.59970457, 0.78504421, 0.20127032],
       [0.03798164, 0.66046409, 0.57573096],
       [0.26389216, 0.59294474, 0.41134653],
       [0.43463029, 0.1772925 , 0.93372019],
       [0.08625034, 0.12583888, 0.63726113]])

#Splitting Arrays

In [33]:
a=np.arange(1,17).reshape((4,4))
print(a,'\n')
[b,c]=np.hsplit(a,2)
print(b,'\n')
print(c,'\n')

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]] 

[[ 1  2]
 [ 5  6]
 [ 9 10]
 [13 14]] 

[[ 3  4]
 [ 7  8]
 [11 12]
 [15 16]] 



# **Pandas**

Series-> pd.Series() is used for creating 1d-array but it has more functionalities than normal 1d-array. It contains two arrays internally

1) index- which holds indxes

2) data-which holds data

In [34]:
import pandas as pd

In [35]:
a=pd.Series([i for i in range(101,111)])
a.values
#we can also change index
a.index=['a','b','c','d','e','f','g','h','i','j']
a

a    101
b    102
c    103
d    104
e    105
f    106
g    107
h    108
i    109
j    110
dtype: int64

In [36]:
random_nums=np.random.randn(10)
a=pd.Series(random_nums)


In [37]:
print(a)
print(a[0:2])

0    1.309423
1    0.240716
2    0.157310
3   -2.131166
4   -0.949493
5    0.212605
6   -0.958475
7   -2.045815
8    1.813033
9   -0.352357
dtype: float64
0    1.309423
1    0.240716
dtype: float64


In [38]:
s=pd.Series([i for i in range(30,35)],index=['a','b','c','d','e'])
s['a']

30

In [39]:
cities=pd.Series(['Maharashtra','Maharashtra','Gujarat','Telengana','UP','UP','Andhra Pardesh'],index=['Pune','Mumbai','Surat','Hyderabad','Lukhnau','Kanpur','Hyderabad'])
print(cities.unique())
print(cities.value_counts())
print(cities.isin([0,0]))

['Maharashtra' 'Gujarat' 'Telengana' 'UP' 'Andhra Pardesh']
Maharashtra       2
UP                2
Gujarat           1
Telengana         1
Andhra Pardesh    1
dtype: int64
Pune         False
Mumbai       False
Surat        False
Hyderabad    False
Lukhnau      False
Kanpur       False
Hyderabad    False
dtype: bool


In [40]:
sample_pd_series=pd.Series([1,2,3,np.NaN,4])
sample_pd_series.notnull()

0     True
1     True
2     True
3    False
4     True
dtype: bool

In [41]:
print(sample_pd_series[sample_pd_series.notnull()]) #only show not null

0    1.0
1    2.0
2    3.0
4    4.0
dtype: float64


How Python Dictionaries work in panda series?

In [42]:
my_dict={'Maharashtra':'Mumbai','Gujarat': 'Gandhinagar','Karnataka': 'Benguluru','Tamilnadu':'Chennai'}
data_dict_pd=pd.Series(my_dict)
print(data_dict_pd)
print(data_dict_pd.index)
print(data_dict_pd.values)

Maharashtra         Mumbai
Gujarat        Gandhinagar
Karnataka        Benguluru
Tamilnadu          Chennai
dtype: object
Index(['Maharashtra', 'Gujarat', 'Karnataka', 'Tamilnadu'], dtype='object')
['Mumbai' 'Gandhinagar' 'Benguluru' 'Chennai']


In [43]:
state_list=['Maharashtra', 'Gujarat', 'Karnataka', 'Tamilnadu','Madhya Pradesh']
data_dict_pd=pd.Series(my_dict,index=state_list)
print(data_dict_pd)

Maharashtra            Mumbai
Gujarat           Gandhinagar
Karnataka           Benguluru
Tamilnadu             Chennai
Madhya Pradesh            NaN
dtype: object


Operations between Series

In [44]:
my_dict1=pd.Series({
    'Meteor350':250000,
    'Classic350':200000,
    'Interceptor650':350000,
    'Himalayan':300000
})
my_dict2=pd.Series({
    'Thunderbird350':200000,
    'Meteor350':10000,
    'Classic350':20000
})
my_dict_sum=my_dict1+my_dict2
print(my_dict_sum)

Classic350        220000.0
Himalayan              NaN
Interceptor650         NaN
Meteor350         260000.0
Thunderbird350         NaN
dtype: float64


# **Dataframe**

In [45]:
data={
    'color'  :['blue','brown','grey','red','green'],
    'bike_name':['Meteor350','Fatbob','Activa','Panigalle','Ninja'],
    'brand':['re','harley','honda','ducati','kawasaki']
}
df=pd.DataFrame(data)
df

color  bike_name     brand
0   blue  Meteor350        re
1  brown     Fatbob    harley
2   grey     Activa     honda
3    red  Panigalle    ducati
4  green      Ninja  kawasaki

In [46]:
df2=pd.DataFrame(data,columns=['bike_name','brand'])
df2

bike_name     brand
0  Meteor350        re
1     Fatbob    harley
2     Activa     honda
3  Panigalle    ducati
4      Ninja  kawasaki

In [47]:
df2.index=['#1','#2','#3','#4','#5']
df2

bike_name     brand
#1  Meteor350        re
#2     Fatbob    harley
#3     Activa     honda
#4  Panigalle    ducati
#5      Ninja  kawasaki

In [48]:
df3=pd.DataFrame(np.arange(0,16).reshape((4,4)),index=['blue','brown','grey','red'],columns=['pen','pencil','notebbok','compass'])
df3


pen  pencil  notebbok  compass
blue     0       1         2        3
brown    4       5         6        7
grey     8       9        10       11
red     12      13        14       15

In [49]:
df3['pen'][2]

8

In [50]:
df3.index.name='colors'
df3.columns.name='items'
df3

items   pen  pencil  notebbok  compass
colors                                
blue      0       1         2        3
brown     4       5         6        7
grey      8       9        10       11
red      12      13        14       15

In [51]:
#creating new column inside df
df3['bag']=3
df3

items   pen  pencil  notebbok  compass  bag
colors                                     
blue      0       1         2        3    3
brown     4       5         6        7    3
grey      8       9        10       11    3
red      12      13        14       15    3

In [52]:
#to change a particular value
print('Before change : \n',df3)
df3['notebbok'][3]=3
print('After Change : \n',df3)

Before change : 
 items   pen  pencil  notebbok  compass  bag
colors                                     
blue      0       1         2        3    3
brown     4       5         6        7    3
grey      8       9        10       11    3
red      12      13        14       15    3
After Change : 
 items   pen  pencil  notebbok  compass  bag
colors                                     
blue      0       1         2        3    3
brown     4       5         6        7    3
grey      8       9        10       11    3
red      12      13         3       15    3


In [53]:
df3.isin([3,'pen'])

items     pen  pencil  notebbok  compass   bag
colors                                        
blue    False   False     False     True  True
brown   False   False     False    False  True
grey    False   False     False    False  True
red     False   False      True    False  True

In [54]:
#deleting a partiular column
del df3['bag']
print(df3)

items   pen  pencil  notebbok  compass
colors                                
blue      0       1         2        3
brown     4       5         6        7
grey      8       9        10       11
red      12      13         3       15


In [55]:
#filtering
df3[df3>5]

items    pen  pencil  notebbok  compass
colors                                 
blue     NaN     NaN       NaN      NaN
brown    NaN     NaN       6.0      7.0
grey     8.0     9.0      10.0     11.0
red     12.0    13.0       NaN     15.0

Dataframe from nested dict

In [56]:
df=pd.DataFrame({
        'red':{2019:18,2020:21,2021:32},
        'green':{2018:45,2019:32,2021:66},
        'blue':{2018:43,2019:89,2020:21,2021:45}
    })
df


red  green  blue
2019  18.0   32.0    89
2020  21.0    NaN    21
2021  32.0   66.0    45
2018   NaN   45.0    43

In [57]:
#transpose of datafarme
df.T

2019  2020  2021  2018
red    18.0  21.0  32.0   NaN
green  32.0   NaN  66.0  45.0
blue   89.0  21.0  45.0  43.0

In [58]:
df.idxmin()

red      2019
green    2019
blue     2020
dtype: int64

In [59]:
df.idxmax()

red      2021
green    2021
blue     2019
dtype: int64

In [60]:
product_df=pd.DataFrame(
    {
        'colors':['red','green','blue','white','black'],
        'price':[10,20,40,70,90],
        'object':['pencil','pen','brush','book','bag'],
    },index=[1,5,6,7,9]
)
product_df

colors  price  object
1    red     10  pencil
5  green     20     pen
6   blue     40   brush
7  white     70    book
9  black     90     bag

In [61]:
#product_df.reindex(range(5),method='ffill',columns=['colors','price','object'])

drop in pandas

pd.drop(index_names,axis)-> 

index : index of column/row

axis: 

  if axis=0 drop row having index=....

  if axis=1 drop column having index=....

for droping row-wise

In [62]:
df=pd.DataFrame(np.arange(2,6),index=['India','Pakistan','Japan','China'])
print(df)
df=df.drop('Pakistan')
print(df)

          0
India     2
Pakistan  3
Japan     4
China     5
       0
India  2
Japan  4
China  5


In [63]:
df=pd.DataFrame(np.arange(16).reshape((4,4)),index=['red','blue','yellow','green'],columns=['pencil','pen','book','bag'])
df

pencil  pen  book  bag
red          0    1     2    3
blue         4    5     6    7
yellow       8    9    10   11
green       12   13    14   15

for droping column wise

In [64]:
df.drop(['pencil','bag'],axis=1)

pen  book
red       1     2
blue      5     6
yellow    9    10
green    13    14

Arithmatic & Data Alingnment

In [65]:
#creating 1 df
df1=pd.DataFrame({
    'value':[900,200,1000,800]
},index=['India','Pakistan','China','UAE']
)
#creating 2nd df
df2=pd.DataFrame({
    'value':[600,800,300,700]
},index=['India','Pakistan','Bangladesh','Bhutan'])
df1+df2
#as bangladesh,uae are not existing in 2nd df so NaN
#only which index are present only those were added in new df

value
Bangladesh     NaN
Bhutan         NaN
China          NaN
India       1500.0
Pakistan    1000.0
UAE            NaN

In [66]:
df1=pd.DataFrame(np.arange(16,32).reshape((4,4)),index=['India','Pakistan','China','USA'],columns=['nukes','guns','misiles','bombs'])
df2=pd.DataFrame(np.arange(32,48).reshape((4,4)),index=['India','Russia','USA','North Korea'],columns=['nukes','guns','misiles','bombs'])
print(df1)
print(df2)
print('df1+df2',df1+df2)

          nukes  guns  misiles  bombs
India        16    17       18     19
Pakistan     20    21       22     23
China        24    25       26     27
USA          28    29       30     31
             nukes  guns  misiles  bombs
India           32    33       34     35
Russia          36    37       38     39
USA             40    41       42     43
North Korea     44    45       46     47
df1+df2              nukes  guns  misiles  bombs
China          NaN   NaN      NaN    NaN
India         48.0  50.0     52.0   54.0
North Korea    NaN   NaN      NaN    NaN
Pakistan       NaN   NaN      NaN    NaN
Russia         NaN   NaN      NaN    NaN
USA           68.0  70.0     72.0   74.0


Function by element

In [68]:
df=pd.DataFrame(np.arange(16).reshape((4,4)),index=['red','green','blue','white'],columns=['bag','pencil','pen','bottle'])
df

bag  pencil  pen  bottle
red      0       1    2       3
green    4       5    6       7
blue     8       9   10      11
white   12      13   14      15

In [69]:
np.sqrt(df)

bag    pencil       pen    bottle
red    0.000000  1.000000  1.414214  1.732051
green  2.000000  2.236068  2.449490  2.645751
blue   2.828427  3.000000  3.162278  3.316625
white  3.464102  3.605551  3.741657  3.872983

we can also apply user-defined functions to our dataframe using apply()

In [70]:
def f(x):
  return x.max()-x.min()
df.apply(f)

bag       12
pencil    12
pen       12
bottle    12
dtype: int64

In [71]:
df.apply(f,axis=1)

red      3
green    3
blue     3
white    3
dtype: int64

it is not necessary that every time apply should return sacler value it can return series also

see below ex.


In [72]:
def f(x):
  return pd.Series([x.min(),x.max()],index=['min','max'])
df.apply(f)

bag  pencil  pen  bottle
min    0       1    2       3
max   12      13   14      15

Statistic functions

In [73]:
df

bag  pencil  pen  bottle
red      0       1    2       3
green    4       5    6       7
blue     8       9   10      11
white   12      13   14      15

In [74]:
df.sum()#col-wise

bag       24
pencil    28
pen       32
bottle    36
dtype: int64

In [76]:
df.sum(axis=1) #row-wise

red       6
green    22
blue     38
white    54
dtype: int64

In [77]:
df.mean()

bag       6.0
pencil    7.0
pen       8.0
bottle    9.0
dtype: float64

In [79]:
df.describe()

bag     pencil        pen     bottle
count   4.000000   4.000000   4.000000   4.000000
mean    6.000000   7.000000   8.000000   9.000000
std     5.163978   5.163978   5.163978   5.163978
min     0.000000   1.000000   2.000000   3.000000
25%     3.000000   4.000000   5.000000   6.000000
50%     6.000000   7.000000   8.000000   9.000000
75%     9.000000  10.000000  11.000000  12.000000
max    12.000000  13.000000  14.000000  15.000000